### ISSUE TITLE
求教：请问事件融合应该使用什么方法？

### ISSUE THREAD

**Issue by Jeafi** [liuhuanyong/CausalityEventExtraction#1]
本人也在进行事理图谱学习，请问事件融合一般使用什么方法？不胜感激

**Comment by jkszw2014** [comment]
基于语义相似度，自己试了一下还行，稍微明显的节点可以融合？请问事件的表示，您用的什么方法？比如
"就是因为人口红利消失" ——>"的从供给侧看，传统的经济增长的不足。"，如何把这两段话精简？
“人口红利消失”——>"经济增长不足"？
